lib: [
  "_build/install/default/lib/language/META"
  "_build/install/default/lib/language/dune-package"
  "_build/install/default/lib/language/opam"
  "_build/install/default/lib/language/peano/peano.a" {"peano/peano.a"}
  "_build/install/default/lib/language/peano/peano.cma" {"peano/peano.cma"}
  "_build/install/default/lib/language/peano/peano.cmi" {"peano/peano.cmi"}
  "_build/install/default/lib/language/peano/peano.cmt" {"peano/peano.cmt"}
  "_build/install/default/lib/language/peano/peano.cmx" {"peano/peano.cmx"}
  "_build/install/default/lib/language/peano/peano.cmxa" {"peano/peano.cmxa"}
  "_build/install/default/lib/language/peano/peano.ml" {"peano/peano.ml"}
]
libexec: [
  "_build/install/default/lib/language/peano/peano.cmxs" {"peano/peano.cmxs"}
]
